### ISSUE TITLE
All beta versions crash when entering world selection screen

### ISSUE THREAD

**Issue by Kaylielotl** [noah1510/sakura-lib#1]
For some reason, version 2.0.0-beta.1, .2 and .3 cause the game to crash upon clicking the singleplayer button on the title screen. May also happen with the multiplayer button, I didn't think to check.

This does not happen with 2.0.0-alpha.10

**Comment by noah1510** [comment]
Could you please provide your logs.
Otherwise its impossible to find the cause.
I played several hours on the beta version and did not encounter such a problem, so its likely an incompatibility with a mod.

**Comment by Kaylielotl** [comment]
Right, sorry, my bad. I knew I was forgetting something.

[Would this suffice?](https://pastebin.com/WVNbxtJv) Or would you rather I share it a different way?

**Comment by noah1510** [comment]
This is an issue with my library mod so I moved the issue.
I think I fixed the problem but I need to update EvenBetterArcheology.
Will be done in a few hours.

**Comment by noah1510** [comment]
It should be fixed in beta.4. Can you test if it works for you now?

**Comment by Kaylielotl** [comment]
Yep, it works now! Thank you!
